/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab11;

public class Library {
	
	public static void main(String arg[]) {
		System.out.println("hello, World");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
